---
title: "Documentation"
---
## Design Details

### Code

The source code for the final project can be found in the team's [Github repository](https://github.com/diego2317/E155-project)

### MCU Design & New Functionality

The MCU has four critical functions. It configures the OV7670 over the SCCB interface, sends a signal to drive XCLK on the OV7670, read bit-masked frames from the FPGA over SPI, and control the position of the robot along the line based on the data from the frames. The new functionality on the MCU was the SCCB peripheral to communicate with the camera, this is similar to I2C protcol, and something that is beyond what we learned in the labs.

### FPGA Design & New Functionality

The FPGA has several critical functions, notably to: read & process pixel data from the OV7670, bitmask the high-dimensional image into binary image, store this over SPRAM, and communicate that data to the MCU over SPI. In order to send pixel data to the MCU, a double SPRAM buffer was implemented. The new functionality on the FPGA was the SPRAM buffer and SPI communication, and this is something that is beyond what we implemented in the labs.

### New Hardware
The main piece of new non-trivial hardware being integrated is the OV7670 camera module, and the SPRAM functionality of the FPGA.